
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  友链: /friends
  关于: /about

subtitle:
  enable: true # 是否开启动效
  text: pbjsjdxwkhqwlfdwlrqphwkrg # 显示的文字
  text2: CDB25B41A49C148C7F41 # 滚动播放，如果不需要可以留空
  text3: C1CE448C7BB387115107 # 最多支持三段文字
  startDelay: 1 # 延迟时间
  typeSpeed: 200 # 打字速度
  loop: true # 是否循环
  backSpeed: 100 # 回退速度
  showCursor: false # 是否显示光标

# 网站图标和侧边栏logo
favicon: /favicon.ico
logo: /images/ayer-side.svg

# 封面配置
# enable-是否启用封面；path-封面背景图；logo-封面logo
cover:
  enable: true
  path: /images/cover1.jpg # /source/images目录下附送多张美图，可更换
  logo: false #/images/ayer.svg，如果不要直接设置成false

progressBar: true

broadcast:
  enable: false # true开启，false关闭
  type: 1 # 1：自定义输入，2：一言api(https://hitokoto.cn/)
  text: 抄的别人的博客, 还未完工, 请不要点击任何外链和打赏, 因为这些可能是原作者留下的 # type为1时有效


excerpt_link: 阅读更多...

excerpt_all: true


copy_btn: true

share_enable: true

share_china: false

share_text: 分享

nav_text:
  page_prev: 上一页
  page_next: 下一页
  post_prev: 上一篇
  post_next: 下一篇

toc: true

image_viewer: true


word_count:
  enable: true
  only_article_visit: true


reward_type: 0

reward_wording: ''

alipay: ''

weixin: ''


copyright_type: 2


search: true


rss: /atom.xml


darkmode: true


canvas_bg: 1

mouse:
  enable: false
  path: /images/mouse.cur


click_effect: 0


layout:
  article_width: 80rem
  sidebar_width: 8rem


github:

  enable: false
  url: https://github.com/Shen-Yu/hexo-theme-ayer


music:
  enable: true
  type: 1
  id: 1394343240 # 网易云分享的音乐ID(更换音乐请更改此配置项)
  autoPlay: false # 是否开启自动播放


busuanzi:
  enable: true


cnzz:
  enable: false
  url: ''


google_analytics: "G-VJ6HK8QB76"

baidu_analytics: ""

# Mathjax数学公式
mathjax: true

# Katex数学公式(allpost设置为false时只有头部设置math:true的文章才开启)
# 需要更换hexo渲染器，npm un hexo-renderer-marked -S && npm i hexo-renderer-markdown-it-katex -S
katex:
  enable: false # true
  allpost: true
  copy_tex: false

# mermaid流程图 三个选项缺一不可(https://mermaid-js.github.io/mermaid/)
mermaid:
  enable: false
  cdn: https://cdn.staticfile.org/mermaid/8.14.0/mermaid.min.js
  theme: forest

# 网站成立年份(默认为 2019，若填入年份小于当前年份，则显示为 2018-2019 类似的格式)
since: 2020


# 友情链接
friends_link:
  Squirre17:
    url: https://squirre17.github.io/
    img: https://squirre17.github.io/imgs/avatar.jpg


# 评论：1、Valine(推荐)；2、Gitalk；3、Twikoo;
 
# 1、Valine[一款快速、简洁且高效的无后端评论系统](https://github.com/xCss/Valine)
# 启用Valine必须先创建leancloud应用， 获取 id|key 填入即可
leancloud:
  enable: false
  app_id: #
  app_key: #
# Valine配置
valine:
  enable: false # 是否启用
  avatar: monsterid # 头像样式(https://valine.js.org/avatar.html)
  placeholder: 给我的文章加点评论吧~ # placeholder

# 2、Gitalk(https://github.com/gitalk/gitalk)
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# 3、Twikoo(https://github.com/imaegoo/twikoo)
twikoo:
  enable: true
  envId: #


ads:



lock:
  enable: false
  password: 123456
  
